### ISSUE TITLE
Handle external charts provided by nats_io

### ISSUE THREAD

**Issue by k15r** [kyma-project/nats-manager#11]
- [x] update local charts based on upstream nats charts
   - PR: https://github.com/kyma-project/nats-manager/pull/13
- [x] copy charts into final image 
- [x] nats manager applies charts to cluster (check details from http://github.com/kyma-project/keda-manager or http://github.com/kyma-project/btp-manager) 
- [x] Add tests for `k8s.KubeClient`

## Acceptance ##
- NATS manager running in a k8s cluster deploys a running NATS cluster with default configuration from image local charts

**Comment by mfaizanse** [comment]
Next steps:
- [ ] Review of PR: https://github.com/kyma-project/nats-manager/pull/18
- [ ] Review of PR: https://github.com/kyma-project/nats-manager/pull/19
