### ISSUE TITLE
decreasing nats cluster size to 1 destroys the cluster

### ISSUE THREAD

**Issue by k15r** [kyma-project/nats-manager#210]
## Description

- enable nats module
- edit the eventing-nats-CR and change cluster size to 1
- result: 1 not-ready eventing-nats-node (the configuration stored in the pvc still holds information that the node was started in clustered mode)

## Mitigation
- prevent changing the nats clustersize for an existing cluster to 1 (once it was !=1)
- for new clusters a size of 1 is fine

**Comment by friedrichwilken** [comment]
> hint: check validation rules
