### ISSUE TITLE
Write integration tests using `envTest` for NATS-manager controller

### ISSUE THREAD

**Issue by mfaizanse** [kyma-project/nats-manager#22]
Write integration tests using envTest for NATS-manager controller

Remember to include tests to cover these scenarios:
- [x] Controller should be able to deploy NATS on an empty cluster.
- [x] Controller should be able to reconcile NATS again. (exisiting cluster must not get into broken state)
- [x] Watching for resource should be working
- [x] apply configuration from cr works
- [x] delete cr also deletes all resources
- [x] updating the cr works

Follow team decisions for test frameworks:
- testify 
- gomega

Ensure tests can be executed in parallel

**Comment by friedrichwilken** [comment]
@mfaizanse have you started to implement this in your previous PRs?
