### ISSUE TITLE
NATS manager deployment uses generic labels for pod selector

### ISSUE THREAD

**Issue by pbochynski** [kyma-project/nats-manager#221]
**Description**
The nats manager deployment contains only one label in selector:
```
control-plane: manager
```
And only that label is set in the pod template. The label is generic and does not identify the pod. 

**Expected result**

Pod selector matches only nats manager pods

**Comment by pbochynski** [comment]
Similar issue to: https://github.com/kyma-project/application-connector-manager/issues/108

**Comment by marcobebway** [comment]
For the time being, we added common labels for the resources managed by the NATS manager.
Updating the selectors will happen in a later ticket which should focus on doing the update without downtime.
