### ISSUE TITLE
setup new pathways for nats manager to release new modules with semantic version

### ISSUE THREAD

**Issue by k15r** [kyma-project/nats-manager#245]
## Description

setup new pipelines following the same pattern as the eventing-manager pipelines

## Acceptance
- [x] artefact created with those pipelines follow the semantic versioning
- [x] release process is documented
- [ ] ~sec-scanner-config.yaml is automatically updated to list the correct images and `rc-tag`~
- [ ] ~remove the .version file if possible~
- [x] all prow job configuration for the release process is only based on the prow-job-yaml not based on any templating mechanism in test-infra (edit this: https://github.com/kyma-project/test-infra/blob/main/prow/jobs/kyma-project/nats-manager/nats-manager-generic.yaml)

**Comment by grischperl** [comment]
Closing this ticket as completed, missing steps will be implemented as part of https://github.com/kyma-project/eventing-manager/issues/359
