### ISSUE TITLE
Fix gh-workflows that uses the Kyma lifecycle-manager to enable NATS

### ISSUE THREAD

**Issue by marcobebway** [kyma-project/nats-manager#290]
**Description**

Fix any gh-workflow which relies on the Kyma lifecycle-manager to enable NATS.

For example (but not limited to):

- https://github.com/kyma-project/nats-manager/blob/main/.github/workflows/pull-with-lifecycle-manager.yaml
- https://github.com/kyma-project/nats-manager/blob/main/.github/workflows/push-with-lifecycle-manager.yaml

The above workflows are using the Kyma lifecycle manager to enable the NATS module, and are using a module-template file (from the latest release) which we do not generate anymore.

**Possible solutions**

- We could generate the module template and apply it as part of the workflow.

**Comment by mfaizanse** [comment]
with lifecycle manager jobs have been updated.
https://github.com/kyma-project/nats-manager/pull/286
