### ISSUE TITLE
bump `prometheus nats exporter` to `v0.14.0`

### ISSUE THREAD

**Issue by friedrichwilken** [kyma-project/nats-manager#293]
**Description**
bump `prometheus nats exporter` to `v0.14.0` https://github.com/nats-io/prometheus-nats-exporter/releases/tag/v0.14.0

**Reasons**

security and performance

**Attachments**

**Comment by k15r** [comment]
released with https://github.com/kyma-project/nats-manager/releases/tag/1.1.0
