### ISSUE TITLE
[EPIC] Setup test infrastructure for nats-manager

### ISSUE THREAD

**Issue by k15r** [kyma-project/nats-manager#39]
We already have:
- unit test
- lint job
- build job (not a kyma module release build job)

What do we need:
- e2e test
- release job (use centrally provided module release mechanism)

Steps:
- [x] #41
- [x] #42
- [x] #40
- [x] #66

**Comment by friedrichwilken** [comment]
this is blocked until we find a replacement for Tekton.

**Comment by muralov** [comment]
> this is blocked until we find a replacement for Tekton.

we use Github Actions
