### ISSUE TITLE
 pod has unbound immediate PersistentVolumeClaims

### ISSUE THREAD

**Issue by luizcarlospedrosogomes** [kyma-project/nats-manager#397]
![image](https://github.com/user-attachments/assets/aea23199-7b65-460a-aa94-76be1c67acdd)

![image](https://github.com/user-attachments/assets/bc07dd20-48e9-492e-bf98-b065f5566807)

 kubectl logs -n kyma-system eventing-nats-0
Defaulted container "config-reloader" out of: config-reloader, metrics, nats, change-storage-permissions (init)
euvds5007x3:~/.kube# kubectl describe pods -n kyma-system eventing-nats-0
Name:                 eventing-nats-0
Namespace:            kyma-system
Priority:             2000000
Priority Class Name:  nats-manager-priority-class
Service Account:      default
Node:                 <none>
Labels:               app.kubernetes.io/component=nats-manager
                      app.kubernetes.io/created-by=nats-manager
                      app.kubernetes.io/instance=eventing
                      app.kubernetes.io/managed-by=nats-manager
                      app.kubernetes.io/name=nats
                      app.kubernetes.io/part-of=nats-manager
                      apps.kubernetes.io/pod-index=0
                      control-plane=nats-manager
                      controller-revision-hash=eventing-nats-7cffcbb668
                      kyma-project.io/dashboard=eventing
                      nats_cluster=eventing-nats
                      statefulset.kubernetes.io/pod-name=eventing-nats-0
Annotations:          kubectl.kubernetes.io/restartedAt: 2024-07-18T02:48:12.497Z
                      prometheus.io/scrape: false
                      sidecar.istio.io/inject: false
Status:               Pending
SeccompProfile:       RuntimeDefault
IP:
IPs:                  <none>
Controlled By:        StatefulSet/eventing-nats
Init Containers:
  change-storage-permissions:
    Image:      europe-docker.pkg.dev/kyma-project/prod/external/alpine:3.19.1
    Port:       <none>
    Host Port:  <none>
    Command:
      sh
      -c
      chown -R 1000:10001 /data && chmod -R 755 /data && echo 'Done!'
    Environment:  <none>
    Mounts:
      /data from eventing-nats-js-pvc (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-plkbp (ro)
Containers:
  config-reloader:
    Image:      europe-docker.pkg.dev/kyma-project/prod/external/natsio/nats-server-config-reloader:0.14.1
    Port:       <none>
    Host Port:  <none>
    Command:
      nats-server-config-reloader
      -pid
      /var/run/nats/nats.pid
      -config
      /etc/nats-config/nats.conf
      -config
      /etc/nats-config/accounts/resolver.conf
    Limits:
      cpu:     50m
      memory:  32Mi
    Requests:
      cpu:        10m
      memory:     20Mi
    Environment:  <none>
    Mounts:
      /etc/nats-config from config-volume (rw)
      /etc/nats-config/accounts from accounts-volume (rw)
      /var/run/nats from pid (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-plkbp (ro)
  metrics:
    Image:      europe-docker.pkg.dev/kyma-project/prod/external/natsio/prometheus-nats-exporter:0.14.0
    Port:       7777/TCP
    Host Port:  0/TCP
    Args:
      -port=7777
      -connz
      -routez
      -subz
      -varz
      -healthz
      -prefix=nats
      -use_internal_server_id
      -jsz=all
      http://localhost:8222/
    Limits:
      cpu:     50m
      memory:  32Mi
    Requests:
      cpu:        10m
      memory:     20Mi
    Environment:  <none>
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-plkbp (ro)
  nats:
    Image:       europe-docker.pkg.dev/kyma-project/prod/external/nats:v20240102-2.10.7-alpine3.18
    Ports:       4222/TCP, 7422/TCP, 7522/TCP, 6222/TCP, 8222/TCP, 7777/TCP
    Host Ports:  0/TCP, 0/TCP, 0/TCP, 0/TCP, 0/TCP, 0/TCP
    Command:
      nats-server
      --config
      /etc/nats-config/nats.conf
    Limits:
      cpu:     500m
      memory:  1Gi
    Requests:
      cpu:      40m
      memory:   64Mi
    Liveness:   http-get http://:8222/healthz%3Fjs-enabled-only=true delay=10s timeout=5s period=30s #success=1 #failure=5
    Readiness:  http-get http://:8222/healthz%3Fjs-server-only=true delay=10s timeout=5s period=10s #success=1 #failure=3
    Startup:    http-get http://:8222/healthz delay=10s timeout=5s period=10s #success=1 #failure=90
    Environment:
      POD_NAME:           eventing-nats-0 (v1:metadata.name)
      POD_NAMESPACE:      kyma-system (v1:metadata.namespace)
      CLUSTER_ADVERTISE:  $(POD_NAME).eventing-nats.$(POD_NAMESPACE).svc.cluster.local
      SERVER_NAME:        $(POD_NAME)
    Mounts:
      /data from eventing-nats-js-pvc (rw)
      /etc/nats-config from config-volume (rw)
      /etc/nats-config/accounts from accounts-volume (rw)
      /var/run/nats from pid (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-plkbp (ro)
Conditions:
  Type           Status
  PodScheduled   False
Volumes:
  eventing-nats-js-pvc:
    Type:       PersistentVolumeClaim (a reference to a PersistentVolumeClaim in the same namespace)
    ClaimName:  eventing-nats-js-pvc-eventing-nats-0
    ReadOnly:   false
  accounts-volume:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  eventing-nats-secret
    Optional:    false
  config-volume:
    Type:      ConfigMap (a volume populated by a ConfigMap)
    Name:      eventing-nats-config
    Optional:  false
  pid:
    Type:       EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:
    SizeLimit:  <unset>
  kube-api-access-plkbp:
    Type:                    Projected (a volume that contains injected data from multiple sources)
    TokenExpirationSeconds:  3607
    ConfigMapName:           kube-root-ca.crt
    ConfigMapOptional:       <nil>
    DownwardAPI:             true
QoS Class:                   Burstable
Node-Selectors:              <none>
Tolerations:                 node.kubernetes.io/not-ready:NoExecute op=Exists for 300s
                             node.kubernetes.io/unreachable:NoExecute op=Exists for 300s
Events:
  Type     Reason            Age    From               Message
  ----     ------            ----   ----               -------
  Warning  FailedScheduling  4m37s  default-scheduler  0/1 nodes are available: pod has unbound immediate PersistentVolumeClaims. preemption: 0/1 nodes are available: 1 Preemption is not helpful for scheduling.

**Comment by the1bit** [comment]
There are no warnings about PersistentVolumeClaims on the NATS manager.

![Image](https://github.com/user-attachments/assets/86a2c150-78bd-42c5-ba72-c9d8672765f0)
![Image](https://github.com/user-attachments/assets/3c11979c-8855-42fe-bdc3-e0b9ae691957)
