### ISSUE TITLE
implementation

### ISSUE THREAD

**Issue by k15r** [kyma-project/nats-manager#4]
- [ ] provision working nats cluster using manager
- [ ] deprovision nats cluster upon CR deletion

Open questions:
- what about the pvc during deprovisioning?
- should existing streams / consumers etc block deprovisioning?

**Comment by friedrichwilken** [comment]
@k15r can you answer these questions?

**Comment by mfaizanse** [comment]
Closing in favor of:
- https://github.com/kyma-project/nats-manager/issues/23
- https://github.com/kyma-project/nats-manager/issues/8
