### ISSUE TITLE
Setup tekton pipeline for nats-manager

### ISSUE THREAD

**Issue by muralov** [kyma-project/nats-manager#42]
# Requirements for tekton pipelines

```mermaid
flowchart TD
Start --> Checkout 
Checkout --> lint
Checkout --> UT[Unit Test]
Checkout --> BM[Build Module]
lint --> upgrade
UT --> upgrade
BM --> upgrade
lint --> e2e
UT --> e2e
BM --> e2e
lint --> SecScan
UT --> SecScan
BM --> SecScan
e2e --> Release[Metadata update for released artefact]
upgrade --> Release[Metadata update for released artefact]
SecScan --> Release[Metadata update for released artefact]
Release --> End
```
 
# Common build pipeline steps:
 
- Check out source code
- Run unit tests
- Lint code 
- Build module (no need for full fledged module with descriptor, as it will be installed without lifecycle manager)
- execute E2E-Test #40 
- upgrade test
- Security scan
- Setup Metadata

**Additional Information:**
https://github.com/kyma-project/test-infra/blob/e1c488d114e663d419099d1297ae82d2102c2593/docs/examples/tekton-demo.yaml#L118

- lint, unit test and build can be executed in parallel
- upgrade test, e2e test, security scan as well

**Comment by k15r** [comment]
Tekton is dead for kyma.
