### ISSUE TITLE
Create build job for OCI module image

### ISSUE THREAD

**Issue by k15r** [kyma-project/nats-manager#75]
**Description**
After building the nats-manager image we need to prepare an actual module out of it.  
The build process it is similar to the one used by [keda](https://github.com/kyma-project/test-infra/blob/main/prow/jobs/modules/external/keda-manager.yaml)

**Hints**
- [ ] manually test the resulting OCI image with lifecycle manager 
- [ ] may require changing the kustomize setup

**Acceptance**
- [ ] OCI image that can be used by kyma-lifecycle manager

**Comment by mfaizanse** [comment]
- [ ] Check run-if-changed.
- [ ] Check kustomization and ENVs provided in manager.yaml.
- [ ] Security, runAsRoot etc.

**Comment by mfaizanse** [comment]
```
# Deploy lifecycle-manager on cluster.
kyma alpha deploy

# Apply a ModuleTemplate CR.
kubectl apply -f {MODULE_TEMPLATE.yaml}

# Enable module.
```
