### ISSUE TITLE
Verify upgrade from kyma (non-modularized nats) -> nats-manager

### ISSUE THREAD

**Issue by k15r** [kyma-project/nats-manager#77]
**Description**

test the initial release of nats manager to existing kyma clusters:

**Acceptance**

- [ ] install nats-manager onto an existing kyma cluster and verify eventing still works 
  - install kyma with production setting for eventing
  - prepare fast-integration for upgrade (limited to testing nats, no switching)
  - install nats-manager as a module using lifecycle manager
  - run fast-integration test to verify that eventing still works (consumer not recreated test enabled)

**Comment by grischperl** [comment]
Blocked until this [issue](https://github.com/kyma-project/nats-manager/issues/75) is merged

**Comment by friedrichwilken** [comment]
Gardener cluster with 3 nodes, k8s 1.26.6

install kyma:
```bash
kyma deploy --source=main -p=production
```

set fi-test to upgrade mode (no backend switching):
```bash
export EVENTING_UPGRADE_JOB='true'
```

set Kyma test type to OSS (not sure if this is required):
```bash
export KYMA_TYPE="OSS"
```

prepare fi-test:
```bash
npm install && npm run eventing-test-prep
```

> the [instructions from the `readme.md`](https://github.com/kyma-project/nats-manager#deploy-nats-manager-with-kyma-lifecycle-manager) are outdated. Follow the [GHA `push-with-lifecycle-manager`](https://github.com/kyma-project/nats-manager/blob/main/.github/workflows/push-with-lifecycle-manager.yaml) instead.

[deploy life-cycle-manager](kyma alpha deploy):
```bash
kyma alpha deploy --ci --force-conflicts
```

download the [latest template](https://github.com/kyma-project/nats-manager/releases/latest/download/module-template.yaml)

apply the template
```bash
kubectl apply -f module-template.yaml
```

run tests:
```
npm run eventing-tests
```

result: tests passed.

**Comment by friedrichwilken** [comment]
### template from main
k8s cluster with 3 nodes, k8s 1.26.6

install kyma:
```bash
kyma deploy --source=main -p=production
```

set fi-test to upgrade mode (no backend switching):
```bash
export EVENTING_UPGRADE_JOB='true'
```

set Kyma test type to OSS (not sure if this is required):
```bash
export KYMA_TYPE="OSS"
```

prepare fi-test:
```bash
npm install && npm run eventing-test-prep
```

> ~~the [instructions from the `readme.md`](https://github.com/kyma-project/nats-manager#deploy-nats-manager-with-kyma-lifecycle-manager) are outdated. Follow the [GHA `push-with-lifecycle-manager`](https://github.com/kyma-project/nats-manager/blob/main/.github/workflows/push-with-lifecycle-manager.yaml) instead.

[deploy life-cycle-manager](kyma alpha deploy):
```bash
kyma alpha deploy --ci --force-conflicts
```

download [the template](https://gcsweb.build.kyma-project.io/gcs/kyma-prow-logs/logs/post-nats-module-build/1696564632564535296/artifacts/) from commit [f937ba0](https://github.com/kyma-project/nats-manager/commit/f937ba0f5a204ac4e513d138779e38bedd82ecb7)

apply the template
```bash
kubectl apply -f module-template.yaml
```

enable the template
```
kyma alpha enable module nats -c fast -n kyma-system
```

wait until it is ready:
```
kubectl get -n kyma-system nats
```

```
$ k get -n kyma-system nats
NAME            STATE        AGE
eventing-nats   Processing   26s
```

```
$ k get -n kyma-system nats
NAME            STATE   AGE
eventing-nats   Ready   5m
```

run tests:
```
npm run eventing-tests
```

result: tests passed.

verify that the `eventing-nats` has an owner reference to the `eventing-nats` CR.
```bash
kubectl get nats eventing-nats -n kyma-system -o=jsonpath='{.metadata.uid}' | diff -u - <(kubectl get sts eventing-nats -n kyma-system -o=jsonpath='{.metadata.ownerReferences[0].uid}')
```

**Comment by mfaizanse** [comment]
Please demo it!
