### ISSUE TITLE
Initial CRD handling

### ISSUE THREAD

**Issue by k15r** [kyma-project/nats-manager#9]
Implement as two independent PRs:

- [x] Implement NATS CRD based on design proposal
- [x] Implement Validation
    - [x] test if CEL-Validation is available in k8s `v1.25`
        ~~- [ ] if not, use Admission control webhook (validating webhook)~~
        - [x] if yes, use CEL-Validation
- [x] Implement defaulting
- [ ] add validation of `memSorage`: dont allow `enable=10` if `size=0` and vice versa
- [ ] add validation of `fileStorage`: make immutable if once set

**Comment by mfaizanse** [comment]
@friedrichwilken Does this [PR](https://github.com/kyma-project/nats-manager/pull/25) cover the 2nd AC `Admission control webhook (validating webhook)`?

**Comment by friedrichwilken** [comment]
@mfaizanse no, as the original task says: `Implement as two independent PRs`,
there will be a second PR for that (that I am working on right now.)

**Comment by friedrichwilken** [comment]
To unblock this, check if validation rules can be used in gardener on a 1.25 cluster.

**Comment by friedrichwilken** [comment]
I used this tutorial to validate that the CEL-validation is working: [CEL-tutorial](https://blog.rewanthtammana.com/kubernetes-crd-validation-with-cel-and-kubebuilder-marker-comments#heading-crd-validation-in-kubernetes-125)
