### ISSUE TITLE
Update eventing to not deploy nats-cluster

### ISSUE THREAD

**Issue by k15r** [kyma-project/nats-manager#96]
**Description**

with nats as a module the eventing component must not deploy a nats cluster when installed.
Remove the nats cluster from the eventing-component resources and check if a nats cluster exists in case eventing is used in nats mode

**Acceptance**
- [x] do not deploy nats cluster as part of eventing component (feature flag)
- [x] check for nats sts/ nats service inside eventing-controller
- [x] exclude all nats resources using helm if-condition
   - [x] K8s secret for NATS server accounts is created by eventing-controller.
- [x] default for the feature flag should be the deployment of all nats resources

>  this feature flag can be controlled using MPS configurations per landscape

**Comment by mfaizanse** [comment]
```
kyma deploy --source=PR-18041 --profile=production --value eventing.global.jetstream.enabled=false
```
